#!/bin/bash
# QUICK START GUIDE - Copy & Paste Commands

echo "=== WALLET SERVICE - QUICK START ==="
echo ""
echo "Location: /Users/administrator/Downloads/P2PTransfer"
echo ""

# Check if we're in the right directory
if [ ! -f "pom.xml" ]; then
    echo "❌ Error: Not in wallet-service directory"
    echo "Run: cd /Users/administrator/Downloads/P2PTransfer"
    exit 1
fi

echo "📋 STEP 1: Build & Run Locally"
echo "================================="
echo ""
echo "Command:"
echo "  docker compose up --build"
echo ""
echo "Or (Maven):"
echo "  mvn clean package"
echo "  java -jar target/wallet-service-1.0.0.jar"
echo ""
echo "Expected: App starts at http://localhost:8080"
echo ""

echo "🧪 STEP 2: Test Concurrency (Different Terminal)"
echo "=================================================="
echo ""
echo "Commands:"
echo "  bash scripts/test_concurrent_wallet_creation.sh http://localhost:8080"
echo "  bash scripts/test_idempotent_transfer.sh http://localhost:8080 1 2"
echo "  bash scripts/test_conservation.sh http://localhost:8080 1 2"
echo ""
echo "Expected: All output ✅ PASS"
echo ""

echo "🚀 STEP 3: Deploy to Free Tier"
echo "================================"
echo ""
echo "1. Initialize git:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial wallet service'"
echo ""
echo "2. Create GitHub public repo and push:"
echo "   git remote add origin https://github.com/YOUR-USERNAME/wallet-service.git"
echo "   git push -u origin main"
echo ""
echo "3. Deploy to Render.com:"
echo "   - Create free PostgreSQL database"
echo "   - Create Web Service from GitHub repo"
echo "   - Set DB environment variables"
echo "   - Deploy"
echo ""
echo "   See: DEPLOYMENT_GUIDE.md for detailed steps"
echo ""

echo "📝 STEP 4: Prepare Submission"
echo "=============================="
echo ""
echo "Deliverables:"
echo "  ✓ Live URL (https://wallet-service-xxx.onrender.com)"
echo "  ✓ Public GitHub repo link"
echo "  ✓ Logs screenshot (platform dashboard)"
echo "  ✓ Burst test screenshot (all 3 passing)"
echo "  ✓ Check REASONING.md is complete"
echo ""

echo "📚 DOCUMENTATION"
echo "================"
echo ""
echo "Start here:"
echo "  • IMPLEMENTATION_COMPLETE.md  - Full summary + checklist"
echo "  • README.md                   - API docs + quick start"
echo "  • REASONING.md                - Design justification (REQUIRED)"
echo "  • DEPLOYMENT_GUIDE.md         - Step-by-step deployment"
echo "  • BUILD_CHECKLIST.md          - File inventory + build steps"
echo ""

echo "💻 API QUICK REFERENCE"
echo "======================"
echo ""
echo "All endpoints require:"
echo "  Authorization: Bearer <user-id>"
echo ""
echo "Create/get wallet:"
echo "  POST /wallets → { id, balance_paise }"
echo ""
echo "Get wallet balance:"
echo "  GET /wallets/{id} → { id, balance_paise }"
echo ""
echo "Transfer money:"
echo "  POST /transfers"
echo "  Body: { from, to, amount_paise, idempotency_key }"
echo "  Response: { transferId, status: SUCCESS|DECLINED, from, to, amount_paise }"
echo ""
echo "Get transfer status:"
echo "  GET /transfers/{id} → { transferId, status, ... }"
echo ""

echo "✨ KEY FEATURES"
echo "==============="
echo ""
echo "✅ Conservation         - sum(balances) never changes"
echo "✅ No overdraft         - balance never negative"
echo "✅ Exactly-once         - same idempotency_key = same result"
echo "✅ Race-free wallets    - one wallet per user always"
echo "✅ Deadlock-free        - sorted-order row locking"
echo "✅ JSON logs            - correlation ID per request"
echo "✅ Metrics              - Prometheus rate, latency, domain counters"
echo "✅ Full deployment      - Docker, docker-compose, free tier ready"
echo ""

echo "🧩 PROJECT STRUCTURE"
echo "===================="
echo ""
echo "24 Java files:"
echo "  • 1 main application class"
echo "  • 3 entities + 1 enum"
echo "  • 3 DTOs (request/response records)"
echo "  • 2 repositories (with pessimistic locking)"
echo "  • 2 services (wallet + transfer - core logic)"
echo "  • 2 controllers (REST endpoints)"
echo "  • 3 exception handlers"
echo "  • 3 filters (bearer token, correlation ID)"
echo ""
echo "Config files:"
echo "  • pom.xml (Maven),"
echo "  • application.yml (Spring Boot)"
echo "  • logback-spring.xml (JSON logging)"
echo ""
echo "Database:"
echo "  • V1__initial_schema.sql (wallet table)"
echo "  • V2__transfer_schema.sql (transfer table)"
echo ""
echo "Tests:"
echo "  • 3 bash burst scripts (concurrency testing)"
echo ""

echo "🎯 SUCCESS CRITERIA"
echo "==================="
echo ""
echo "✓ Local build & test pass"
echo "  docker compose up --build"
echo "  bash scripts/test_*.sh http://localhost:8080 → all ✅ PASS"
echo ""
echo "✓ Deploy to free tier"
echo "  Live URL responds: curl <URL>/actuator/health → UP"
echo ""
echo "✓ Burst tests pass against live URL"
echo "  bash scripts/test_*.sh <LIVE_URL> → all ✅ PASS"
echo ""
echo "✓ Write-up complete"
echo "  REASONING.md addresses 8 sections (see header)"
echo ""

echo "⚠️  FREE TIER NOTES"
echo "=================="
echo ""
echo "Cost: ₹0/month"
echo "  • Render app tier (550 free hours/month)"
echo "  • Render PostgreSQL (256 MB free)"
echo "  • No credit card required"
echo ""
echo "Performance:"
echo "  • Free tier may be slow (shared resources)"
echo "  • Burst tests may take 30-60s"
echo "  • If timeout, add -m 60 to curl commands"
echo ""

echo ""
echo "🎉 Ready to go!"
echo "================"
echo ""
echo "Next command:"
echo "  cd /Users/administrator/Downloads/P2PTransfer && docker compose up --build"
echo ""
echo "Then in another terminal:"
echo "  bash scripts/test_concurrent_wallet_creation.sh http://localhost:8080"
echo ""
echo "Expected output: ✅ PASS"
echo ""

